[tool.poetry]
name = "battlepoops"
version = "0.1.0"
description = ""
authors = ["Tblast <nguyen-thien@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
